-- H2, дисковая реляционная база. Связь: один автор — несколько книг.
CREATE TABLE IF NOT EXISTS authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    country VARCHAR(80) NOT NULL,
    birth_year INTEGER NOT NULL CHECK (birth_year > 0)
);
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    published_year INTEGER NOT NULL CHECK (published_year > 0),
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    stock INTEGER NOT NULL CHECK (stock >= 0),
    author_id BIGINT NOT NULL REFERENCES authors(id)
);
